backend:
  name: github
  repo: darrylmorley/ss-gridsome
  branch: master

media_folder: "static/uploads"
public_folder: "/uploads"

media_library:
  name: cloudinary
  config:
    cloud_name: shooting-supplies
    api_key: 796925918192138

collections:
  - name: "Post"
    label: "Posts"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "date" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }

publish_mode: editorial_workflow
